


[sample]
  name = "20240905_DR4_5Q4C_0430#7"

[path]
    config = "C:\\Users\\quant\\SynologyDrive\\09 Data\\Fridge Data\\Qubit\\20240905_DR3_5Q4C_0430#7\\config\\20240905_DR4_5Q4C_0430#7.json"
    dynamic_config = "C:\\Users\\quant\\SynologyDrive\\09 Data\\Fridge Data\\Qubit\\20240905_DR3_5Q4C_0430#7\\config\\20240905_DR4_5Q4C_0430#7_config.pkl"
    specification = "C:\\Users\\quant\\SynologyDrive\\09 Data\\Fridge Data\\Qubit\\20240905_DR3_5Q4C_0430#7\\config\\20240905_DR4_5Q4C_0430#7_spec.pkl"
    output_root = "C:\\Users\\quant\\SynologyDrive\\09 Data\\Fridge Data\\Qubit\\20240905_DR3_5Q4C_0430#7\\raw_data"


